#!/bin/bash
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
set -o vi
TOP="\[\e]0;\u@\h:\w\a\]"
export PS1="$TOP${debian_chroot:+($debian_chroot)}\[\033[01;32m\]$\[\033[00m\] "
# export PS1="\[\033[01;34m\]\$\[\033[00m\] "
export DENO_INSTALL="/home/ryanwhite04/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"

